export const CATEGORIES = ['Men', 'Women', 'Kids', 'Beauty'];

const makeProduct = (p) => p;

const imagesFromSeeds = (seedNames) => seedNames.map((s) => `https://picsum.photos/seed/${s}/400/500`);




const imagesForProduct = (category, name) => {
  // Special-case: remove the inappropriate beach/bikini image
  if (name === 'H&M Linen Blend Trousers') {
    return imagesFromSeeds(['trouser1', 'trouser2', 'trouser3']);
  }

  // Per requirement, each product gets 3 images using ONLY the category seeds:
  // Men: man1/man2/man3 (and man4/man5 exist but not used here)
  // Women: woman1/woman2/woman3 (woman4 exists but not used here)
  // Kids: child1/child2/child3
  // Beauty: beauty1/beauty2/beauty3 (beauty4 exists but not used here)
  // Footwear: shoe1/shoe2/shoe3
  // Accessories: style1/style2/style3
  const seedsByCategory = {
    Men: ['man1', 'man2', 'man3'],
    Women: ['woman1', 'woman2', 'woman3'],
    Kids: ['child1', 'child2', 'child3'],
    Beauty: ['beauty1', 'beauty2', 'beauty3'],
    Footwear: ['shoe1', 'shoe2', 'shoe3'],
    Accessories: ['style1', 'style2', 'style3'],
  };

  const seeds = seedsByCategory[category] || seedsByCategory.Men;
  return imagesFromSeeds(seeds);
};



export const PRODUCTS = [
  makeProduct({
    id: 'p1',
    name: 'Roadster Slim Fit Shirt',
    brand: 'Roadster',
    category: 'Men',

    price: 799,
    mrp: 1299,
    rating: 4.4,
    popularity: 91,
    arrival: '2026-05-10',
    discountPercent: 38,
    description: 'Breathable cotton blend with a crisp slim silhouette for everyday comfort.',
    material: 'Cotton Blend',
    care: 'Machine wash cold. Do not bleach.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    images: imagesForProduct('Men', 'Roadster Slim Fit Shirt'),
  }),
  makeProduct({
    id: 'p2',
    name: 'H&M Linen Blend Trousers',
    brand: 'H&M',
    category: 'Men',

    price: 1299,
    mrp: 2199,
    rating: 4.6,
    popularity: 86,
    arrival: '2026-04-28',
    discountPercent: 41,
    description: 'Lightweight linen blend trousers with an effortless drape and a premium feel.',
    material: 'Linen Blend',
    care: 'Gentle wash. Dry in shade.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: imagesForProduct('Men', 'H&M Linen Blend Trousers'),
  }),
  makeProduct({
    id: 'p3',
    name: 'Levi’s Blue Denim Jeans',
    brand: 'Levi’s',
    category: 'Men',
    price: 2499,
    mrp: 3999,
    rating: 4.5,
    popularity: 94,
    arrival: '2026-03-21',
    discountPercent: 38,
    description: 'Classic blue denim with a comfortable stretch for all-day wear.',
    material: 'Denim with Stretch',
    care: 'Wash inside out. Tumble dry low.',
    sizes: ['28', '30', '32', '34', '36'],
    images: imagesForProduct('Men', 'Levi’s Blue Denim Jeans'),
  }),
  makeProduct({
    id: 'p4',
    name: 'Nike Air Runner Sneakers',
    brand: 'Nike',
    category: 'Men',
    price: 4999,
    mrp: 6999,
    rating: 4.7,
    popularity: 99,
    arrival: '2026-05-02',
    discountPercent: 29,
    description: 'Cushioned comfort with responsive cushioning for daily runs and walks.',
    material: 'Synthetic Upper',
    care: 'Wipe clean. Air dry.',
    sizes: ['7', '8', '9', '10', '11', '12'],
    images: imagesForProduct('Men', 'Nike Air Runner Sneakers'),
  }),
  makeProduct({
    id: 'p5',
    name: 'Puma Everyday Sneakers',
    brand: 'Puma',
    category: 'Women',
    price: 3499,
    mrp: 4999,
    rating: 4.3,
    popularity: 87,
    arrival: '2026-04-10',
    discountPercent: 30,
    description: 'Lightweight sneakers with breathable comfort and a sleek finish.',
    material: 'Mesh + Synthetic',
    care: 'Spot clean. Do not machine wash.',
    sizes: ['5', '6', '7', '8', '9'],
    images: imagesForProduct('Women', 'Puma Everyday Sneakers'),
  }),
  makeProduct({
    id: 'p6',
    name: 'Myntra Essentials Cotton Dress',
    brand: 'Myntra Essentials',
    category: 'Women',
    price: 1099,
    mrp: 1999,
    rating: 4.6,
    popularity: 83,
    arrival: '2026-05-18',
    discountPercent: 45,
    description: 'Soft cotton dress with a flattering fit and breathable feel.',
    material: '100% Cotton',
    care: 'Machine wash cold. Iron low.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: imagesForProduct('Women', 'Myntra Essentials Cotton Dress'),
  }),
  makeProduct({
    id: 'p7',
    name: 'Zudio Printed Kurti',
    brand: 'Zudio',
    category: 'Women',
    price: 699,
    mrp: 1299,
    rating: 4.2,
    popularity: 76,
    arrival: '2026-02-19',
    discountPercent: 46,
    description: 'Bright print kurti with easy everyday styling and comfort.',
    material: 'Rayon',
    care: 'Gentle wash. Wash with similar colors.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: imagesForProduct('Women', 'Zudio Printed Kurti'),
  }),
  makeProduct({
    id: 'p8',
    name: 'HRX Sports Jacket',
    brand: 'HRX',
    category: 'Men',
    price: 2199,
    mrp: 3299,
    rating: 4.4,
    popularity: 88,
    arrival: '2026-05-06',
    discountPercent: 33,
    description: 'Premium sports jacket with breathable lining and a modern cut.',
    material: 'Polyester',
    care: 'Machine wash. Tumble dry low.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: imagesForProduct('Men', 'HRX Sports Jacket'),
  }),
  makeProduct({
    id: 'p9',
    name: 'Biba Chikankari Kurta',
    brand: 'Biba',
    category: 'Women',
    price: 1899,
    mrp: 2899,
    rating: 4.8,
    popularity: 95,
    arrival: '2026-04-02',
    discountPercent: 34,
    description: 'Intricate Chikankari work with a graceful fit for festive days.',
    material: 'Cotton',
    care: 'Dry clean recommended.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: imagesForProduct('Women', 'Biba Chikankari Kurta'),
  }),
  makeProduct({
    id: 'p10',
    name: 'Soyul Lightweight Sandals',
    brand: 'Soyul',
    category: 'Women',
    price: 899,
    mrp: 1499,
    rating: 4.1,
    popularity: 72,
    arrival: '2026-01-30',
    discountPercent: 40,
    description: 'Everyday sandals with a cushioned footbed for comfort all day.',
    material: 'PU + Textile',
    care: 'Wipe clean with damp cloth.',
    sizes: ['5', '6', '7', '8', '9'],
    images: imagesForProduct('Women', 'Soyul Lightweight Sandals'),
  }),

  // Kids
  makeProduct({
    id: 'p11',
    name: 'Allen Solly Junior T-Shirt',
    brand: 'Allen Solly Junior',
    category: 'Kids',
    price: 499,
    mrp: 899,
    rating: 4.6,
    popularity: 82,
    arrival: '2026-05-01',
    discountPercent: 44,
    description: 'Soft cotton tee with vibrant prints—easy to wear and easy to wash.',
    material: 'Cotton',
    care: 'Machine wash cold. Iron low.',
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: imagesForProduct('Kids', 'Allen Solly Junior T-Shirt'),
  }),
  makeProduct({
    id: 'p12',
    name: 'Nike Kids Training Shoes',
    brand: 'Nike',
    category: 'Kids',
    price: 1799,
    mrp: 2599,
    rating: 4.5,
    popularity: 85,
    arrival: '2026-04-15',
    discountPercent: 31,
    description: 'Comfortable training shoes with durable grip for active kids.',
    material: 'Synthetic',
    care: 'Wipe clean. Air dry.',
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y'],
    images: imagesForProduct('Kids', 'Nike Kids Training Shoes'),
  }),
  makeProduct({
    id: 'p13',
    name: 'Levi’s Kids Denim Shorts',
    brand: 'Levi’s',
    category: 'Kids',
    price: 799,
    mrp: 1299,
    rating: 4.3,
    popularity: 74,
    arrival: '2026-03-12',
    discountPercent: 38,
    description: 'Denim shorts made for summer—comfortable fit and durable fabric.',
    material: 'Denim',
    care: 'Machine wash. Wash inside out.',
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: imagesForProduct('Kids', 'Levi’s Kids Denim Shorts'),
  }),
  makeProduct({
    id: 'p14',
    name: 'Adidas Junior Hoodie',
    brand: 'Adidas',
    category: 'Kids',
    price: 999,
    mrp: 1599,
    rating: 4.7,
    popularity: 90,
    arrival: '2026-05-14',
    discountPercent: 38,
    description: 'Cozy hoodie with a soft fleece lining and a sporty look.',
    material: 'Fleece Blend',
    care: 'Machine wash. Tumble dry low.',
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: imagesForProduct('Kids', 'Adidas Junior Hoodie'),
  }),

  // Beauty
  makeProduct({
    id: 'p15',
    name: 'Plum BodyLovin’ Strawberry Shampoo',
    brand: 'Plum',
    category: 'Beauty',
    price: 349,
    mrp: 499,
    rating: 4.6,
    popularity: 92,
    arrival: '2026-05-20',
    discountPercent: 30,
    description: 'Gentle shampoo with strawberry goodness for fresh, healthy hair.',
    material: 'Hair Care',
    care: 'Use regularly. Avoid direct eye contact.',
    sizes: ['250ml'],
    images: imagesForProduct('Beauty', 'Plum BodyLovin’ Strawberry Shampoo'),
  }),
  makeProduct({
    id: 'p16',
    name: 'Nivea Soft Moisturizer',
    brand: 'Nivea',
    category: 'Beauty',
    price: 299,
    mrp: 399,
    rating: 4.4,
    popularity: 84,
    arrival: '2026-04-18',
    discountPercent: 25,
    description: 'Lightweight moisturiser for smooth, soft skin with everyday hydration.',
    material: 'Skin Care',
    care: 'Apply to clean skin as needed.',
    sizes: ['200ml'],
    images: imagesForProduct('Beauty', 'Nivea Soft Moisturizer'),
  }),
  makeProduct({
    id: 'p17',
    name: 'Lakme 9to5 Liquid Lipstick',
    brand: 'Lakme',
    category: 'Beauty',
    price: 499,
    mrp: 799,
    rating: 4.5,
    popularity: 89,
    arrival: '2026-03-28',
    discountPercent: 38,
    description: 'Long-lasting matte liquid lipstick with a comfortable wear.',
    material: 'Makeup',
    care: 'Avoid prolonged sun exposure. Store cool & dry.',
    sizes: ['1pc'],
    images: imagesForProduct('Beauty', 'Lakme 9to5 Liquid Lipstick'),
  }),
  makeProduct({
    id: 'p18',
    name: 'Mamaearth Ubtan Face Wash',
    brand: 'Mamaearth',
    category: 'Beauty',
    price: 279,
    mrp: 399,
    rating: 4.3,
    popularity: 78,
    arrival: '2026-04-22',
    discountPercent: 30,
    description: 'Ubtan face wash for a refreshed look and gentle daily cleansing.',
    material: 'Skin Care',
    care: 'Use morning and evening. Rinse thoroughly.',
    sizes: ['100g'],
    images: imagesForProduct('Beauty', 'Mamaearth Ubtan Face Wash'),
  }),
  makeProduct({
    id: 'p19',
    name: 'Philips Hair Straightener',
    brand: 'Philips',
    category: 'Beauty',
    price: 1599,
    mrp: 2499,
    rating: 4.6,
    popularity: 88,
    arrival: '2026-05-08',
    discountPercent: 36,
    description: 'Smoothens hair with adjustable heat and salon-like results.',
    material: 'Appliance',
    care: 'Unplug after use. Clean plates with dry cloth.',
    sizes: ['1pc'],
    images: imagesForProduct('Beauty', 'Philips Hair Straightener'),
  }),

  // More products to reach 24+
  makeProduct({
    id: 'p20',
    name: 'Zudio Chino Casual Pants',
    brand: 'Zudio',
    category: 'Men',
    price: 999,
    mrp: 1599,
    rating: 4.2,
    popularity: 73,
    arrival: '2026-02-10',
    discountPercent: 38,
    description: 'Chino pants for casual day-outs with a clean tailored finish.',
    material: 'Cotton Blend',
    care: 'Machine wash. Iron medium.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: imagesForProduct('Men', 'Zudio Chino Casual Pants'),
  }),
  makeProduct({
    id: 'p21',
    name: 'Roadster Oversized Tee',
    brand: 'Roadster',
    category: 'Women',
    price: 549,
    mrp: 899,
    rating: 4.1,
    popularity: 70,
    arrival: '2026-05-12',
    discountPercent: 39,
    description: 'Relaxed oversized tee with a soft finish and everyday style.',
    material: 'Cotton',
    care: 'Machine wash cold.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: imagesForProduct('Women', 'Roadster Oversized Tee'),
  }),
  makeProduct({
    id: 'p22',
    name: 'Puma Graphic Sweatshirt',
    brand: 'Puma',
    category: 'Men',
    price: 1399,
    mrp: 2299,
    rating: 4.4,
    popularity: 80,
    arrival: '2026-04-30',
    discountPercent: 39,
    description: 'Warm sweatshirt with a premium graphic print for a street-ready look.',
    material: 'Fleece',
    care: 'Machine wash. Do not tumble dry high.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: imagesForProduct('Men', 'Puma Graphic Sweatshirt'),
  }),
  makeProduct({
    id: 'p23',
    name: 'H&M Kids Denim Jacket',
    brand: 'H&M',
    category: 'Kids',
    price: 999,
    mrp: 1599,
    rating: 4.5,
    popularity: 81,
    arrival: '2026-05-03',
    discountPercent: 37,
    description: 'Classic denim jacket with comfy fit—perfect for cool evenings.',
    material: 'Denim',
    care: 'Machine wash cold. Hang dry.',
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: imagesForProduct('Kids', 'H&M Kids Denim Jacket'),
  }),
  makeProduct({
    id: 'p24',
    name: 'Lakme Kajal Eye Liner',
    brand: 'Lakme',
    category: 'Beauty',
    price: 399,
    mrp: 649,
    rating: 4.2,
    popularity: 77,
    arrival: '2026-03-14',
    discountPercent: 38,
    description: 'Smudge-resistant kajal with a smooth glide for intense definition.',
    material: 'Makeup',
    care: 'Close cap after use. Store in cool & dry place.',
    sizes: ['1pc'],
    images: imagesForProduct('Beauty', 'Lakme Kajal Eye Liner'),
  }),
  makeProduct({
    id: 'p25',
    name: 'Nivea Lip Balm Hydration',
    brand: 'Nivea',
    category: 'Beauty',
    price: 199,
    mrp: 299,
    rating: 4.6,
    popularity: 84,
    arrival: '2026-05-16',
    discountPercent: 33,
    description: 'Nourishing lip balm to keep lips soft and hydrated.',
    material: 'Skin Care',
    care: 'Apply frequently. Keep away from heat.',
    sizes: ['12g'],
    images: imagesForProduct('Beauty', 'Nivea Lip Balm Hydration'),
  })
];

export function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}

export function allBrands() {
  return Array.from(new Set(PRODUCTS.map((p) => p.brand))).sort();
}

